name: Wellness Way CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # === Frontend Steps ===
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      # === Backend Steps ===
      - name: Install Backend Dependencies
        working-directory: ./Backend
        run: npm install

      - name: Run Backend Tests (skip if none)
        working-directory: ./Backend
        run: npm test || echo "No backend tests found"

      # === Deploy Frontend to GitHub Pages ===
      - name: Deploy Frontend to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          # if you using vite project then it will create dist folder when you build otherwise it create build folfer [pleae chk]
          publish_dir: ./frontend/dist 
